### PR TITLE
Allow this tool to be used with more recent versions of BeautifulSoup

### PR DESCRIPTION
**Pull request by Lucas-C**
This would allow the use of extra powerful selectors: https://www.crummy.com/software/BeautifulSoup/bs4/doc/#css-selectors

### CODE REVIEW

**Comment by plainas** [comment]
Hi Lucas,

I don't want to have non fixed dependency version definition due to stability. People would end up with different versions of beautiful soup and its dependencies. Eventually backwards compatibility would be broken and we would be in a mess.

That said, those selectors are do offer and useful functionality.

Did you try installing with a more recent version of BeautifulSoup? Which one? If everything works, we should update to a specific version that works and get the fancy selectors.

On this topic, I came across an alternative to beautifulsoup the other day which claimed better performance and less dependency hell. Beautifulsoup dependencies are a wasteland. I would certainly be glad into reducing the size of the dependency tree, but I can't find now.

**Comment by Lucas-C** [comment]
I think that maybe here the fundamental issue is the lack of non-regression tests, ensuring that upgrading the dependencies will not break the program.

Hence I added NR tests and configuration for Travis CI. Here is the resulting output: https://travis-ci.org/Lucas-C/tq

What do you think ? I can still lock the version to `4.8.1` if you prefer.

**Comment by plainas** [comment]
Thank you for the tests and the script. I love the minimal to-the-point approach you took. I will start adding some myself too, now that the basic test flow is in place.

I prefer locking the dependencies because of the previously stated reason.

I'll merge this manually as there are a couple of things I would like to amend:
* support for python2  does more harm than good at this day and age. Python2 had a great run, let's all give it a cozy place in our memory and all, but no need to be held back by it.
* i still use the `tqtest` script to manually test things out. Although something like `run_tq` might be a more appropriate

About `sys.stdin.buffer` vs `sys.stdin.read()`, do these behave differently? Are there advantages of one over the other?

**Comment by Lucas-C** [comment]
I made the requested changes ;)

I had used `sys.stdin.read()` for the compatibility with Python 2, so I got back to your original code.

**Comment by Lucas-C** [comment]
@plainas do you need me to make additional changes to this PR ?

**Comment by plainas** [comment]
I wanted to merge this branch manually because I wanted to leave some changes out. Specifically, travis build file and pylint. But it might be time to step things up a little.

I have never really bothered publishing code to pypi. There's a whole amount of meta-work that just doesn't appeal to me. But since this project appear to have caught the interest of a few people out there, let's do it. Can this be automated by travis? We could have a branch pushing a new version to pypi each time we merge to it. probably ''stable''.

I'll create a develop branch too so we can land the pull requests there quicker without changing maser, which is the branch shown by default when one browses to this project's page.

Thanks for the PR. The tests are a much welcome addition

**Pull request merged**
